-- Criação da tabela de usuários
CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOTO_PERFIL VARCHAR(255),
    SEGUIDORES INT NOT NULL DEFAULT 0
);

-- Criação da tabela de eventos
CREATE TABLE EVENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(200) NOT NULL,
    DESCRICAO TEXT,
    DATA_INICIO TIMESTAMP NOT NULL,
    DATA_FIM TIMESTAMP NOT NULL,
    LOCAL VARCHAR(200) NOT NULL,
    GENERO VARCHAR(100),
    VALOR DECIMAL(10, 2) NOT NULL,
    IMAGEM VARCHAR(255),
    PARTICIPANTES INT NOT NULL DEFAULT 0,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ORGANIZADOR_ID INT NOT NULL,
    FOREIGN KEY (ORGANIZADOR_ID) REFERENCES USUARIO(ID)
);

-- Criação da tabela de avaliações
CREATE TABLE AVALIACAO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EVENTO_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    NOTA INT NOT NULL,
    COMENTARIO TEXT,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO(ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

-- Criação da tabela de comentários
CREATE TABLE COMENTARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EVENTO_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    COMENTARIO TEXT,
    COMENTARIO_PAI_ID INT,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COMENTARIO_PAI_ID) REFERENCES COMENTARIO(ID),
    FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO(ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

-- Criação da tabela de postagens
CREATE TABLE PUBLICACAO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EVENTO_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    CONTEUDO TEXT,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOTOS VARCHAR(255),
    FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO(ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

-- Tabela de participantes de eventos
CREATE TABLE PARTICIPANTE_EVENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EVENTO_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDENTE', -- CONFIRMADO, CANCELADO, PENDENTE
    FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO(ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    UNIQUE KEY UK_PARTICIPANTE_EVENTO (EVENTO_ID, USUARIO_ID)
);

-- Tabela de seguidores
CREATE TABLE SEGUIDOR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SEGUIDOR_ID INT NOT NULL, -- Usuário que está seguindo
    SEGUIDO_ID INT NOT NULL, -- Usuário que está sendo seguido
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SEGUIDOR_ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (SEGUIDO_ID) REFERENCES USUARIO(ID),
    UNIQUE KEY UK_SEGUIDOR (SEGUIDOR_ID, SEGUIDO_ID)
);

