-- Criação da tabela de usuários
CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Criação da tabela de eventos
CREATE TABLE EVENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(200) NOT NULL,
    DESCRICAO TEXT,
    DATA_INICIO TIMESTAMP NOT NULL,
    DATA_FIM TIMESTAMP NOT NULL,
    LOCAL VARCHAR(200) NOT NULL,
    CAPACIDADE_MAXIMA INT NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ORGANIZADOR_ID INT NOT NULL,
    FOREIGN KEY (ORGANIZADOR_ID) REFERENCES USUARIO(ID)
);

-- Criação da tabela de inscrições
CREATE TABLE INSCRICAO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EVENTO_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    DATA_INSCRICAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) NOT NULL,
    FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO(ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID),
    UNIQUE (EVENTO_ID, USUARIO_ID)
); 